name = input("Enter your name\n")
print("Hello ", name, "welcome to the interview!")
question1 = input("How do you manage stress?\n")
print("Wow! ", question1, "That is a good way managing it.")
question2= input("what makes you unique?\n")
print("Wow! ", question2, "Thats something very unique")
question3 = input("How do feel about working with others?\n")
print("Wow! ", question3, "That is a good way of working with other people.")
question4 = input("How do you manage your anger?\n")
print("Wow! ", question4, "Thats something very good")
question5 = input("what motives you\n")
print("Wow! ", question5, "That is something very common that motivates people to work on our company")
